version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_DB: gorbunov
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: 
      dockerfile: ./Dockerfile
    container_name: python_app
    networks:
      - default
    depends_on:
      - postgres

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
