CREATE TABLE IF NOT EXISTS test_table (name VARCHAR(10) NOT NULL, surname VARCHAR(15) NOT NULL, city VARCHAR(20) NOT NULL, age INTEGER NOT NULL);
INSERT INTO test_table (name, surname, city, age) VALUES ('Dmitry', 'Gorbunov', 'Kazan', 114);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Gerasimov', 'Nizhny Novgorod', 108);
INSERT INTO test_table (name, surname, city, age) VALUES ('Konstantin', 'Karavaev', 'Samara', 46);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Gerasimov', 'Vologda', 82);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Sokolov', 'Novosibirsk', 38);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Karavaev', 'Omsk', 120);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Kolotilov', 'Nizhny Novgorod', 64);
INSERT INTO test_table (name, surname, city, age) VALUES ('Konstantin', 'Sokolov', 'Saint Petersburg', 150);
INSERT INTO test_table (name, surname, city, age) VALUES ('Dmitry', 'Gerasimov', 'Samara', 14);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Gorbunov', 'Moscow', 90);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Sokolov', 'Moscow', 74);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Efimov', 'Novosibirsk', 106);
INSERT INTO test_table (name, surname, city, age) VALUES ('Konstantin', 'Kulnevsky', 'Nizhny Novgorod', 70);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Sokolov', 'Samara', 104);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Ivanov', 'Ekaterinburg', 22);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Sekushin', 'Moscow', 36);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Sekushin', 'Novosibirsk', 12);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Smirnov', 'Moscow', 124);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Kulnevsky', 'Nizhny Novgorod', 100);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Sekushin', 'Ekaterinburg', 108);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Gerasimov', 'Omsk', 122);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Gerasimov', 'Kazan', 78);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Karavaev', 'Kazan', 4);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Smirnov', 'Novosibirsk', 86);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Ivanov', 'Chelyabinsk', 148);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Gorbunov', 'Omsk', 108);
INSERT INTO test_table (name, surname, city, age) VALUES ('Dmitry', 'Gerasimov', 'Vologda', 98);
INSERT INTO test_table (name, surname, city, age) VALUES ('Konstantin', 'Kulnevsky', 'Novosibirsk', 26);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Kolotilov', 'Saint Petersburg', 126);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Karavaev', 'Saint Petersburg', 108);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Sekushin', 'Moscow', 122);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Kulnevsky', 'Samara', 136);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Efimov', 'Saint Petersburg', 80);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Sekushin', 'Samara', 14);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Sokolov', 'Vologda', 64);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Sekushin', 'Vologda', 58);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Gorbunov', 'Saint Petersburg', 72);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Gorbunov', 'Nizhny Novgorod', 86);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Sokolov', 'Chelyabinsk', 110);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Kulnevsky', 'Samara', 128);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Gerasimov', 'Moscow', 130);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Smirnov', 'Kazan', 142);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Gerasimov', 'Chelyabinsk', 24);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Smirnov', 'Novosibirsk', 68);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Sokolov', 'Ekaterinburg', 110);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Sokolov', 'Chelyabinsk', 26);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Ivanov', 'Chelyabinsk', 16);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Karavaev', 'Nizhny Novgorod', 88);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Karavaev', 'Vologda', 96);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Kolotilov', 'Nizhny Novgorod', 56);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Efimov', 'Omsk', 148);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Sokolov', 'Vologda', 32);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Kolotilov', 'Chelyabinsk', 140);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Smirnov', 'Saint Petersburg', 142);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Gerasimov', 'Kazan', 52);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Kolotilov', 'Omsk', 136);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Smirnov', 'Ekaterinburg', 116);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Gorbunov', 'Novosibirsk', 122);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Gorbunov', 'Moscow', 128);
INSERT INTO test_table (name, surname, city, age) VALUES ('Konstantin', 'Karavaev', 'Chelyabinsk', 80);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Kulnevsky', 'Vologda', 38);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Sekushin', 'Moscow', 8);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Smirnov', 'Vologda', 2);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Sekushin', 'Vologda', 30);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Gorbunov', 'Nizhny Novgorod', 100);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Smirnov', 'Novosibirsk', 124);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Karavaev', 'Omsk', 76);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Gorbunov', 'Novosibirsk', 138);
INSERT INTO test_table (name, surname, city, age) VALUES ('Konstantin', 'Ivanov', 'Kazan', 28);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Gerasimov', 'Samara', 46);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Kulnevsky', 'Saint Petersburg', 102);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Ivanov', 'Vologda', 26);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Kulnevsky', 'Saint Petersburg', 112);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Gerasimov', 'Ekaterinburg', 138);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Sekushin', 'Ekaterinburg', 28);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Karavaev', 'Omsk', 58);
INSERT INTO test_table (name, surname, city, age) VALUES ('Dmitry', 'Smirnov', 'Kazan', 78);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Karavaev', 'Samara', 132);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Smirnov', 'Ekaterinburg', 84);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Gorbunov', 'Omsk', 132);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Efimov', 'Moscow', 114);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Efimov', 'Novosibirsk', 138);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Sekushin', 'Samara', 66);
INSERT INTO test_table (name, surname, city, age) VALUES ('Sergey', 'Gorbunov', 'Saint Petersburg', 126);
INSERT INTO test_table (name, surname, city, age) VALUES ('Igor', 'Sekushin', 'Novosibirsk', 42);
INSERT INTO test_table (name, surname, city, age) VALUES ('Dmitry', 'Sekushin', 'Novosibirsk', 46);
INSERT INTO test_table (name, surname, city, age) VALUES ('Kirill', 'Gerasimov', 'Vologda', 20);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexey', 'Gorbunov', 'Vologda', 100);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Sekushin', 'Moscow', 130);
INSERT INTO test_table (name, surname, city, age) VALUES ('Stepan', 'Karavaev', 'Nizhny Novgorod', 76);
INSERT INTO test_table (name, surname, city, age) VALUES ('Maxim', 'Karavaev', 'Samara', 2);
INSERT INTO test_table (name, surname, city, age) VALUES ('Alexander', 'Gerasimov', 'Omsk', 70);
INSERT INTO test_table (name, surname, city, age) VALUES ('Yuri', 'Sokolov', 'Chelyabinsk', 44);
